apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo HELLOO && sleep 36000']
    volumeMounts:
      - name: myvolume
        mountPath: /data
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: pvc

