- name: install nginx webserver
  apt:
    name: nginx

- name: start nginx
  shell: systemctl start nginx

- name: nginx config file
  template:
    src: nginx-config.j2
    dest: /etc/nginx/conf.d/{{ domain_name }}.conf
  notify: Restart Nginx

- name: configure the index.html file
  template:
    src: nginx-index-file.j2
    dest: /var/www/{{ domain_name }}/index.html
