global:
  resolve_timeout: 5m

route:
  receiver: 'discord'
  group_wait: 10s
  group_interval: 5s
  repeat_interval: 1h

receivers:
  - name: 'discord'
    webhook_configs:
      - url: "http://discord-proxy:5000/webhook"
        send_resolved: true
