global:
  scrape_interval: 15s



alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
rule_files:
  - "alert_rules.yml"


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "dns-server-exporter"
    static_configs:
      - targets: ["192.168.171.132:9100"]
  - job_name: "docker-container-exporter"
    static_configs:
      - targets: ["192.168.171.129:8080"] 
  - job_name: "k8s-cadvisor"
    static_configs:
      - targets: ["192.168.171.142:8080"] 
  - job_name: "k8s-node-exporter"
    static_configs:
      - targets: ["192.168.171.142:9100"] 
  - job_name: "k8s-kube-state"
    static_configs:
      - targets: ["192.168.171.142:30002"] 
